# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from student_account import StudentAccount


class UiDialogAdd(object):
    # receives the info from the user and creates a StudentAccount object which adds info to database
    def submit_record(self):
        if self.line_edit.text() != "" and self.line_edit_2.text() != "" and self.line_edit_3.text() != "":
            try:
                student = StudentAccount(self.line_edit.text(), self.line_edit_2.text(), self.line_edit_3.text())
                show_msg = QMessageBox(QMessageBox.Information, 'Success',
                                                            "Thank you! A record was added to the database successfully!",
                                                            QMessageBox.Ok)
                show_msg.exec_()
                self.line_edit.clear()
                self.line_edit_2.clear()
                self.line_edit_3.clear()
            except:
                show_msg = QMessageBox(QMessageBox.Critical, 'Error',
                                       "Unknown error adding to database!",
                                       QMessageBox.Ok)
                show_msg.exec_()

        else:
            show_msg = QMessageBox(QMessageBox.Critical, 'Error',
                                   "Please fill in all parts before submitting",
                                   QMessageBox.Ok)
            show_msg.exec_()

    def setup_ui(self, dialog):
        dialog.setObjectName("Dialog")
        dialog.resize(400, 300)
        dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        dialog.setAcceptDrops(False)
        dialog.setAccessibleName("")
        dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        dialog.setWindowFilePath("")
        self.button_box = QtWidgets.QDialogButtonBox(dialog)
        self.button_box.setGeometry(QtCore.QRect(40, 240, 331, 32))
        self.button_box.setStyleSheet("background-color: rgb(0, 170, 255);\n"
        "color: white;")
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 41))
        self.label.setObjectName("label")
        self.line_edit = QtWidgets.QLineEdit(dialog)
        self.line_edit.setGeometry(QtCore.QRect(110, 90, 171, 21))
        self.line_edit.setText("")
        self.line_edit.setObjectName("line_edit")
        self.line_edit_2 = QtWidgets.QLineEdit(dialog)
        self.line_edit_2.setGeometry(QtCore.QRect(110, 130, 171, 21))
        self.line_edit_2.setText("")
        self.line_edit_2.setObjectName("line_edit_2")
        self.line_edit_3 = QtWidgets.QLineEdit(dialog)
        self.line_edit_3.setGeometry(QtCore.QRect(110, 170, 171, 21))
        self.line_edit_3.setText("")
        self.line_edit_3.setObjectName("line_edit_3")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(dialog)
        self.line.setGeometry(QtCore.QRect(10, 50, 381, 21))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslate_ui(dialog)
        self.button_box.accepted.connect(self.submit_record)
        self.button_box.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslate_ui(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("Dialog", "Accounts Manager"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">Add Student</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "First Name"))
        self.label_3.setText(_translate("Dialog", "Last Name"))
        self.label_4.setText(_translate("Dialog", "Admittance Year"))
