# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog
import resources  # generated after adding graphics to your UI in Pyqt Designer
from db_manager import DBManager
import sys
from add_student import UiDialogAdd
from id_search import UiSearch
from name_search import UiDialogName
from student_account import StudentAccount


class UiMainWindow(QMainWindow):
    def __init__(self):
        # This is needed here to inherit methods and data from QMainWindow
        super().__init__()
        self._system_name = "Student Account Management System (SAMS)"
        self.setup_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update
        self.retranslate_ui(self)  # This method was provided by PyQt Designer. Note the snake_case update
        self.load_records()

# adds the list of students provided into the db
    def load_records(self):
        db_manager = DBManager()
        db_manager.init_tables()  # initialize your init_tables
        # process the lists and load data into your DB
        names = ["Willena Shupe", "Jolanda Agin", "Leta Stacker", "Leonora Oliverio", "Birgit Stoudt", "Aron Valtierra",
                 "Vi Buschman", "Janee Barnwell", "Agnus Flower", "Byron Mccartney", "Victoria Crabill", "Amy Swinton",
                 "Arla Mohamed", "Bryon Vester", "Lue Benway", "Mozelle Macauley", "Suzann Galindo", "Delicia Barriere",
                 "Marcella Uyehara", "Jane Curley"]
        admittance_years = [2020, 2019, 2016, 2019, 2013, 2014, 2014, 2018, 2016, 2012, 2014, 2015, 2018, 2013, 2019,
                            2017,
                            2019, 2020, 2015, 2013]
        # Adds the list provided to add all the people
        for i in range(0, len(names), 1):
            new_student = StudentAccount(names[i].split()[0], names[i].split()[1], admittance_years[i])

# shows the add_student GUI by creating a new instance of it
    def show_add_student(self):
        try:
            dialog = QDialog()
            dialog.ui = UiDialogAdd()
            dialog.ui.setup_ui(dialog)
            dialog.setAttribute(QtCore.Qt.WA_DeleteOnClose)
            dialog.exec_()
        except Exception:
            raise Exception

# shows the id_search GUI by creating a new instance of it
    def show_search_id(self):
        try:
            dialog = QDialog()
            dialog.ui = UiSearch()
            dialog.ui.setup_ui(dialog)
            dialog.setAttribute(QtCore.Qt.WA_DeleteOnClose)
            dialog.exec_()
        except Exception:
            raise Exception

# shows the name_search GUI by creating a new instance of it
    def show_search_name(self):
        try:
            dialog = QDialog()
            dialog.ui = UiDialogName()
            dialog.ui.setup_ui(dialog)
            dialog.setAttribute(QtCore.Qt.WA_DeleteOnClose)
            dialog.exec_()
        except Exception:
            raise Exception

    def setup_ui(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(806, 681)
        self.central_widget = QtWidgets.QWidget(mainwindow)
        self.central_widget.setObjectName("central_widget")
        self.background_img = QtWidgets.QLabel(self.central_widget)
        self.background_img.setGeometry(QtCore.QRect(0, -20, 861, 651))
        self.background_img.setAutoFillBackground(False)
        self.background_img.setStyleSheet("background-color: black;\n""\n""")
        self.background_img.setScaledContents(True)
        self.background_img.setWordWrap(False)
        self.background_img.setOpenExternalLinks(False)
        self.background_img.setObjectName("background_img")
        self.title_label = QtWidgets.QLabel(self.central_widget)
        self.title_label.setGeometry(QtCore.QRect(100, 70, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.add_student = QtWidgets.QPushButton(self.central_widget)
        self.add_student.setGeometry(QtCore.QRect(70, 180, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_student.setFont(font)
        self.add_student.setStyleSheet("background-color: rgb(255, 170, 255);\n""border-radius: 16px;\n""")
        self.add_student.setObjectName("add_student")
        self.search_id = QtWidgets.QPushButton(self.central_widget)
        self.search_id.setGeometry(QtCore.QRect(310, 180, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_id.setFont(font)
        self.search_id.setStyleSheet("background-color: rgb(255, 170, 255);\n""border-radius: 16px;\n""")
        self.search_id.setObjectName("search_id")
        self.search_name = QtWidgets.QPushButton(self.central_widget)
        self.search_name.setGeometry(QtCore.QRect(550, 180, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_name.setFont(font)
        self.search_name.setStyleSheet("background-color: rgb(255, 170, 255);\n""border-radius: 16px;\n""")
        self.search_name.setObjectName("search_name")
        self.quit = QtWidgets.QPushButton(self.central_widget)
        self.quit.setGeometry(QtCore.QRect(640, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.quit.setFont(font)
        self.quit.setStyleSheet("background-color: rgb(190, 255, 146);\n""\n""")
        self.quit.setObjectName("quit")
        mainwindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        # adds event listeners to the buttons
        self.add_student.clicked.connect(self.show_add_student)
        self.search_id.clicked.connect(self.show_search_id)
        self.search_name.clicked.connect(self.show_search_name)
        self.quit.clicked.connect(sys.exit)

        self.retranslate_ui(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslate_ui(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "mainwindow"))
        self.background_img.setText(_translate("mainwindow", "<html><head/><body><p><img src=\":/background_img/photo-1485841890310-6a055c88698a.jpg\"/></p></body></html>"))
        self.title_label.setText(_translate("mainwindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Student Account Management System</span></p></body></html>"))
        self.add_student.setText(_translate("mainwindow", "Add Student"))
        self.search_id.setText(_translate("mainwindow", "Search by ID"))
        self.search_name.setText(_translate("mainwindow", "Search by Name"))
        self.quit.setText(_translate("mainwindow", "Quit"))


def main():
    app = QApplication(sys.argv)
    ui = UiMainWindow()  # creates an instance of the MainUI
    ui.show()
    sys.exit(app.exec())


main()


# import python_final_rc
