# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_manager import DBManager


class UiDialogName(object):
    def get_student(self):
        text = self.line_edit.text()
        db = DBManager()
        db.open_connection()
        result = db.search_by_name(text)
        self.table_widget.setRowCount(len(result))
        self.table_widget.setColumnCount(6)

        j = 0
        for row_data in result:
            i = 0
            for data in row_data:
                self.table_widget.setItem(j, i, QtWidgets.QTableWidgetItem(str(data)))
                i = i + 1
            j = j + 1

        db.close_connection()

    def setup_ui(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(567, 458)
        self.table_widget = QtWidgets.QTableWidget(dialog)
        self.table_widget.setGeometry(QtCore.QRect(10, 140, 541, 241))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(dialog)
        self.line.setGeometry(QtCore.QRect(10, 50, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 380, 541, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.push_button = QtWidgets.QPushButton(dialog)
        self.push_button.setGeometry(QtCore.QRect(444, 402, 91, 41))
        self.push_button.setStyleSheet("background-color: rgb(0, 170, 255);color: rgb(255, 255, 255);font-size: 16px;")
        self.push_button.setObjectName("push_button")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_edit = QtWidgets.QLineEdit(dialog)
        self.line_edit.setGeometry(QtCore.QRect(140, 80, 381, 21))
        self.line_edit.setObjectName("line_edit")

        self.push_button.setAutoDefault(False)
        self.push_button.clicked.connect(dialog.close)
        self.line_edit.returnPressed.connect(self.get_student)

        self.retranslate_ui(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslate_ui(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Search by Name"))
        self.label.setText(_translate("dialog", "Search by Name"))
        self.push_button.setText(_translate("dialog", "Exit"))
        self.label_2.setText(_translate("dialog", "Student Name"))
